
var MeshGenerator = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,v,ba=new Promise((a,b)=>{aa=a;v=b}),ca=Object.assign({},h),da="./this.program",w="",ea;"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptName&&(w=_scriptName);w.startsWith("blob:")?w="":w=w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1);ea=(a,b,c)=>{fetch(a,{credentials:"same-origin"}).then(d=>d.ok?d.arrayBuffer():Promise.reject(Error(d.status+" : "+d.url))).then(b,c)};var fa=h.print||console.log.bind(console),x=h.printErr||console.error.bind(console);
Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);var y;h.wasmBinary&&(y=h.wasmBinary);var ha,ia=!1,A,C,D,E,F,G,ja,ka,la=[],ma=[],na=[],pa=!1;function qa(){var a=h.preRun.shift();la.unshift(a)}var H=0,ra=null,I=null;function sa(a){h.onAbort?.(a);a="Aborted("+a+")";x(a);ia=!0;a+=". Build with -sASSERTIONS for more info.";pa&&ta();a=new WebAssembly.RuntimeError(a);v(a);throw a;}var ua=a=>a.startsWith("data:application/octet-stream;base64,"),va;
function wa(a){if(a==va&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}function xa(a){return y?Promise.resolve().then(()=>wa(a)):new Promise((b,c)=>{ea(a,d=>b(new Uint8Array(d)),()=>{try{b(wa(a))}catch(d){c(d)}})})}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{x(`failed to asynchronously prepare wasm: ${d}`);sa(d)})}
function za(a,b){var c=va;return y||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){x(`wasm streaming compile failed: ${f}`);x("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}
var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba,J=a=>{for(var b="";C[a];)b+=Ba[C[a++]];return b},K={},L={},M={},O,Ca=a=>{throw new O(a);},Da,Ea=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Da("Mismatched type converter count");for(var l=0;l<d.length;++l)P(d[l],k[l])}var d=[];d.forEach(function(k){M[k]=a});var f=Array(a.length),g=[],n=0;a.forEach((k,l)=>{L.hasOwnProperty(k)?f[l]=L[k]:(g.push(k),K.hasOwnProperty(k)||(K[k]=[]),K[k].push(()=>{f[l]=L[k];++n;n===g.length&&c(f)}))});0===g.length&&
c(f)};function Fa(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(L.hasOwnProperty(a)){if(c.Y)return;throw new O(`Cannot register type '${d}' twice`);}L[a]=b;delete M[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(f=>f()))}function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Fa(a,b,c)}
var Ga=[],Q=[],Ha=a=>{9<a&&0===--Q[a+1]&&(Q[a]=void 0,Ga.push(a))},R=a=>{if(!a)throw new O("Cannot use deleted val. handle = "+a);return Q[a]},S=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ga.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}};function Ia(a){return this.fromWireType(G[a>>2])}
var Ja={name:"emscripten::val",fromWireType:a=>{var b=R(a);Ha(a);return b},toWireType:(a,b)=>S(b),argPackAdvance:8,readValueFromPointer:Ia,R:null},Ka=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ja[c>>2])};case 8:return function(c){return this.fromWireType(ka[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},T=(a,b)=>Object.defineProperty(b,"name",{value:a}),La=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ma(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].R)return!0;return!1}function Na(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=T(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Oa=(a,b)=>{if(void 0===h[a].O){var c=h[a];h[a]=function(...d){if(!h[a].O.hasOwnProperty(d.length))throw new O(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].O})!`);return h[a].O[d.length].apply(this,d)};h[a].O=[];h[a].O[c.X]=c}},Pa=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].O&&void 0!==h[a].O[c])throw new O(`Cannot register public name '${a}' twice`);Oa(a,a);if(h.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].O[c]=b}else h[a]=b,void 0!==c&&(h[a].da=c)},Qa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Ra,Sa=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,h["dynCall_"+a])(b,...c)):b=Ra.get(b)(...c);return b},Ta=(a,b)=>(...c)=>Sa(a,b,c),Ua=(a,b)=>{a=J(a);var c=a.includes("j")?Ta(a,b):Ra.get(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);return c},Va,Za=a=>{a=Wa(a);var b=J(a);U(a);return b},$a=(a,b)=>{function c(g){f[g]||L[g]||(M[g]?
M[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Va(`${a}: `+d.map(Za).join([", "]));},ab=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},bb=(a,b,c)=>{switch(b){case 1:return c?d=>A[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},cb=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);
g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}},db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},eb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,V=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=
d);)++c;if(16<c-b&&a.buffer&&eb)return eb.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var n=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|n:(f&7)<<18|g<<12|n<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},fb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,gb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=
d)&&E[c];)++c;c<<=1;if(32<c-a&&fb)return fb.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=D[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},hb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)D[b>>1]=a.charCodeAt(f),b+=2;D[b>>1]=0;return b-d},ib=a=>2*a.length,jb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var f=F[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d},
kb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},mb={},nb=a=>{var b=mb[a];return void 0===b?J(a):b},ob=[],pb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),qb=a=>{var b=ob.length;ob.push(a);
return b},rb=(a,b)=>{var c=L[a];if(void 0===c)throw a=`${b} has unknown type ${Za(a)}`,new O(a);return c},sb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=rb(G[b+4*d>>2],"parameter "+d);return c},tb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(G[b>>2]=S(d));return a},ub={},wb=()=>{if(!vb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},
b;for(b in ub)void 0===ub[b]?delete a[b]:a[b]=ub[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);vb=c}return vb},vb,xb=[null,[],[]],W=a=>0===a%4&&(0!==a%100||0===a%400),yb=[31,29,31,30,31,30,31,31,30,31,30,31],zb=[31,28,31,30,31,30,31,31,30,31,30,31];function Ab(a){var b=Array(db(a)+1);cb(a,b,0,b.length);return b}
for(var Bb=(a,b,c,d)=>{function f(e,q,t){for(e="number"==typeof e?e.toString():e||"";e.length<q;)e=t[0]+e;return e}function g(e,q){return f(e,q,"0")}function n(e,q){function t(z){return 0>z?-1:0<z?1:0}var u;0===(u=t(e.getFullYear()-q.getFullYear()))&&0===(u=t(e.getMonth()-q.getMonth()))&&(u=t(e.getDate()-q.getDate()));return u}function k(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function l(e){var q=e.S;for(e=new Date((new Date(e.T+1900,0,1)).getTime());0<q;){var t=e.getMonth(),u=(W(e.getFullYear())?yb:zb)[t];if(q>u-e.getDate())q-=u-e.getDate()+1,e.setDate(1),11>t?e.setMonth(t+1):(e.setMonth(0),e.setFullYear(e.getFullYear()+1));else{e.setDate(e.getDate()+q);break}}t=new Date(e.getFullYear()+1,0,4);q=k(new Date(e.getFullYear(),0,
4));t=k(t);return 0>=n(q,e)?0>=n(t,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var m=G[d+40>>2];d={ba:F[d>>2],aa:F[d+4>>2],U:F[d+8>>2],W:F[d+12>>2],V:F[d+16>>2],T:F[d+20>>2],P:F[d+24>>2],S:F[d+28>>2],ea:F[d+32>>2],$:F[d+36>>2],ca:m?m?V(C,m):"":""};c=c?V(C,c):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");m={"%a":e=>B[e.P].substring(0,3),"%A":e=>B[e.P],"%b":e=>r[e.V].substring(0,3),"%B":e=>r[e.V],"%C":e=>g((e.T+1900)/100|0,2),"%d":e=>
g(e.W,2),"%e":e=>f(e.W,2," "),"%g":e=>l(e).toString().substring(2),"%G":l,"%H":e=>g(e.U,2),"%I":e=>{e=e.U;0==e?e=12:12<e&&(e-=12);return g(e,2)},"%j":e=>{for(var q=0,t=0;t<=e.V-1;q+=(W(e.T+1900)?yb:zb)[t++]);return g(e.W+q,3)},"%m":e=>g(e.V+1,2),"%M":e=>g(e.aa,2),"%n":()=>"\n","%p":e=>0<=e.U&&12>e.U?"AM":"PM","%S":e=>g(e.ba,2),"%t":()=>"\t","%u":e=>e.P||7,"%U":e=>g(Math.floor((e.S+7-e.P)/7),2),"%V":e=>{var q=Math.floor((e.S+7-(e.P+6)%7)/7);2>=(e.P+371-e.S-2)%7&&q++;if(q)53==q&&(t=(e.P+371-e.S)%7,
4==t||3==t&&W(e.T)||(q=1));else{q=52;var t=(e.P+7-e.S-1)%7;(4==t||5==t&&W(e.T%400-1))&&q++}return g(q,2)},"%w":e=>e.P,"%W":e=>g(Math.floor((e.S+7-(e.P+6)%7)/7),2),"%y":e=>(e.T+1900).toString().substring(2),"%Y":e=>e.T+1900,"%z":e=>{e=e.$;var q=0<=e;e=Math.abs(e)/60;return(q?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":e=>e.ca,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](d)));c=c.replace(/\0\0/g,"%");p=Ab(c);if(p.length>b)return 0;
A.set(p,a);return p.length-1},Cb=Array(256),X=0;256>X;++X)Cb[X]=String.fromCharCode(X);Ba=Cb;O=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Da=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Q.push(0,1,void 0,1,null,1,!0,1,!1,1);h.count_emval_handles=()=>Q.length/2-5-Ga.length;
Va=h.UnboundTypeError=((a,b)=>{var c=T(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Eb={q:()=>{sa("")},p:()=>{},z:(a,b,c,d)=>{b=J(b);P(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(f){return this.fromWireType(C[f])},R:null})},y:a=>P(a,Ja),j:(a,b,c)=>{b=J(b);P(a,{name:b,fromWireType:d=>d,toWireType:(d,f)=>f,argPackAdvance:8,readValueFromPointer:Ka(b,c),R:null})},f:(a,b,c,d,f,g,n)=>{var k=Qa(b,c);a=J(a);a=ab(a);f=Ua(d,f);Pa(a,function(){$a(`Cannot call ${a} due to unbound types`,k)},b-1);Ea(k,
l=>{var m=a;var p=a;l=[l[0],null].concat(l.slice(1));var B=f,r=l.length;if(2>r)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var e=null!==l[1]&&!1,q=Ma(l),t="void"!==l[0].name;B=[p,Ca,B,g,La,l[0],l[1]];for(var u=0;u<r-2;++u)B.push(l[u+2]);if(!q)for(u=e?1:2;u<l.length;++u)null!==l[u].R&&B.push(l[u].R);q=Ma(l);u=l.length;var z="",N="";for(r=0;r<u-2;++r)z+=(0!==r?", ":"")+"arg"+r,N+=(0!==r?", ":"")+"arg"+r+"Wired";z=`\n        return function (${z}) {\n        if (arguments.length !== ${u-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${u-2}');\n        }`;q&&(z+="var destructors = [];\n");var Xa=q?"destructors":"null",oa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");e&&(z+="var thisWired = classParam['toWireType']("+Xa+", this);\n");for(r=0;r<u-2;++r)z+="var arg"+r+"Wired = argType"+r+"['toWireType']("+Xa+", arg"+r+");\n",oa.push("argType"+r);e&&(N="thisWired"+(0<N.length?
", ":"")+N);z+=(t||n?"var rv = ":"")+"invoker(fn"+(0<N.length?", ":"")+N+");\n";if(q)z+="runDestructors(destructors);\n";else for(r=e?1:2;r<l.length;++r)e=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==l[r].R&&(z+=`${e}_dtor(${e});\n`,oa.push(`${e}_dtor`));t&&(z+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Ya,Fb]=[oa,z+"}\n"];Ya.push(Fb);l=Na(Ya)(...B);p=T(p,l);l=b-1;if(!h.hasOwnProperty(m))throw new Da("Replacing nonexistent public symbol");void 0!==h[m].O&&void 0!==l?h[m].O[l]=p:
(h[m]=p,h[m].X=l);return[]})},b:(a,b,c,d,f)=>{b=J(b);-1===f&&(f=4294967295);f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g}var n=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};P(a,{name:b,fromWireType:f,toWireType:n,argPackAdvance:8,readValueFromPointer:bb(b,c,0!==d),R:null})},a:(a,b,c)=>{function d(g){return new f(A.buffer,G[g+4>>2],G[g>>2])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=J(c);P(a,{name:c,fromWireType:d,
argPackAdvance:8,readValueFromPointer:d},{Y:!0})},k:(a,b)=>{b=J(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var f=G[d>>2],g=d+4;if(c)for(var n=g,k=0;k<=f;++k){var l=g+k;if(k==f||0==C[l]){n=n?V(C,n,l-n):"";if(void 0===m)var m=n;else m+=String.fromCharCode(0),m+=n;n=l+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(C[g+k]);m=m.join("")}U(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"==typeof f;if(!(g||f instanceof
Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array))throw new O("Cannot pass non-string to std::string");var n=c&&g?db(f):f.length;var k=Db(4+n+1),l=k+4;G[k>>2]=n;if(c&&g)cb(f,C,l,n+1);else if(g)for(g=0;g<n;++g){var m=f.charCodeAt(g);if(255<m)throw U(l),new O("String has UTF-16 code units that do not fit in 8 bits");C[l+g]=m}else for(g=0;g<n;++g)C[l+g]=f[g];null!==d&&d.push(U,k);return k},argPackAdvance:8,readValueFromPointer:Ia,R(d){U(d)}})},e:(a,b,c)=>{c=J(c);if(2===b){var d=gb;
var f=hb;var g=ib;var n=k=>E[k>>1]}else 4===b&&(d=jb,f=kb,g=lb,n=k=>G[k>>2]);P(a,{name:c,fromWireType:k=>{for(var l=G[k>>2],m,p=k+4,B=0;B<=l;++B){var r=k+4+B*b;if(B==l||0==n(r))p=d(p,r-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=p),p=r+b}U(k);return m},toWireType:(k,l)=>{if("string"!=typeof l)throw new O(`Cannot pass non-string to C++ string type ${c}`);var m=g(l),p=Db(4+m+b);G[p>>2]=m/b;f(l,p+4,m+b);null!==k&&k.push(U,p);return p},argPackAdvance:8,readValueFromPointer:Ia,R(k){U(k)}})},A:(a,b)=>
{b=J(b);P(a,{Z:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},d:(a,b,c,d,f)=>{a=ob[a];b=R(b);c=nb(c);return a(b,b[c],d,f)},B:Ha,m:a=>{if(0===a)return S(pb());a=nb(a);return S(pb()[a])},c:(a,b,c)=>{b=sb(a,b);var d=b.shift();a--;var f="return function (obj, func, destructorsRef, args) {\n",g=0,n=[];0===c&&n.push("obj");for(var k=["retType"],l=[d],m=0;m<a;++m)n.push("arg"+m),k.push("argType"+m),l.push(b[m]),f+=`  var arg${m} = argType${m}.readValueFromPointer(args${g?"+"+g:""});\n`,
g+=b[m].argPackAdvance;f+=`  var rv = ${1===c?"new func":"func.call"}(${n.join(", ")});\n`;d.Z||(k.push("emval_returnValue"),l.push(tb),f+="  return emval_returnValue(retType, destructorsRef, rv);\n");k.push(f+"};\n");a=Na(k)(...l);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return qb(T(c,a))},h:(a,b)=>{a=R(a);b=R(b);return S(a[b])},i:a=>{9<a&&(Q[a+1]+=1)},l:a=>S(nb(a)),n:a=>{var b=R(a);La(b);Ha(a)},g:(a,b)=>{a=rb(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},
x:()=>{sa("OOM")},s:(a,b)=>{var c=0;wb().forEach((d,f)=>{var g=b+c;f=G[a+4*f>>2]=g;for(g=0;g<d.length;++g)A[f++]=d.charCodeAt(g);A[f]=0;c+=d.length+1});return 0},t:(a,b)=>{var c=wb();G[a>>2]=c.length;var d=0;c.forEach(f=>d+=f.length+1);G[b>>2]=d;return 0},u:()=>52,w:()=>52,o:function(){return 70},v:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var n=G[b>>2],k=G[b+4>>2];b+=8;for(var l=0;l<k;l++){var m=C[n+l],p=xb[a];0===m||10===m?((1===a?fa:x)(V(p,0)),p.length=0):p.push(m)}f+=k}G[d>>2]=f;return 0},r:(a,b,c,
d)=>Bb(a,b,c,d)},Y=function(){function a(c){Y=c.exports;ha=Y.C;c=ha.buffer;h.HEAP8=A=new Int8Array(c);h.HEAP16=D=new Int16Array(c);h.HEAPU8=C=new Uint8Array(c);h.HEAPU16=E=new Uint16Array(c);h.HEAP32=F=new Int32Array(c);h.HEAPU32=G=new Uint32Array(c);h.HEAPF32=ja=new Float32Array(c);h.HEAPF64=ka=new Float64Array(c);Ra=Y.G;ma.unshift(Y.D);H--;h.monitorRunDependencies?.(H);0==H&&(null!==ra&&(clearInterval(ra),ra=null),I&&(c=I,I=null,c()));return Y}var b={a:Eb};H++;h.monitorRunDependencies?.(H);if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){x(`Module.instantiateWasm callback failed with error: ${c}`),v(c)}va||=ua("MeshGenerator.wasm")?"MeshGenerator.wasm":h.locateFile?h.locateFile("MeshGenerator.wasm",w):w+"MeshGenerator.wasm";za(b,function(c){a(c.instance)}).catch(v);return{}}(),Wa=a=>(Wa=Y.E)(a),Db=a=>(Db=Y.F)(a),U=a=>(U=Y.H)(a),ta=()=>(ta=Y.I)();h.dynCall_viijii=(a,b,c,d,f,g,n)=>(h.dynCall_viijii=Y.J)(a,b,c,d,f,g,n);h.dynCall_jiji=(a,b,c,d,f)=>(h.dynCall_jiji=Y.K)(a,b,c,d,f);
h.dynCall_iiiiij=(a,b,c,d,f,g,n)=>(h.dynCall_iiiiij=Y.L)(a,b,c,d,f,g,n);h.dynCall_iiiiijj=(a,b,c,d,f,g,n,k,l)=>(h.dynCall_iiiiijj=Y.M)(a,b,c,d,f,g,n,k,l);h.dynCall_iiiiiijj=(a,b,c,d,f,g,n,k,l,m)=>(h.dynCall_iiiiiijj=Y.N)(a,b,c,d,f,g,n,k,l,m);var Z;I=function Gb(){Z||Hb();Z||(I=Gb)};
function Hb(){function a(){if(!Z&&(Z=!0,h.calledRun=!0,!ia)){pa=!0;Aa(ma);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();na.unshift(b)}Aa(na)}}if(!(0<H)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)qa();Aa(la);0<H||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Hb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = MeshGenerator;
else if (typeof define === 'function' && define['amd'])
  define([], () => MeshGenerator);
