
var MeshGenerator = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var h=moduleArg,aa,v;h.ready=new Promise((a,b)=>{aa=a;v=b});var ba=Object.assign({},h),ca="./this.program",w="";"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptDir&&(w=_scriptDir);w.startsWith("blob:")?w="":w=w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1);var da=h.print||console.log.bind(console),x=h.printErr||console.error.bind(console);Object.assign(h,ba);ba=null;h.thisProgram&&(ca=h.thisProgram);var y;h.wasmBinary&&(y=h.wasmBinary);
"object"!=typeof WebAssembly&&A("no native wasm support detected");var ea,fa=!1,C,D,E,F,G,H,ha,ia,ja=[],ka=[],la=[],ma=!1;function na(){var a=h.preRun.shift();ja.unshift(a)}var I=0,pa=null,J=null;function A(a){h.onAbort?.(a);a="Aborted("+a+")";x(a);fa=!0;a+=". Build with -sASSERTIONS for more info.";ma&&qa();a=new WebAssembly.RuntimeError(a);v(a);throw a;}var ra=a=>a.startsWith("data:application/octet-stream;base64,"),K;K="MeshGenerator.wasm";
if(!ra(K)){var sa=K;K=h.locateFile?h.locateFile(sa,w):w+sa}function ta(a){if(a==K&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}function ua(a){return y||"function"!=typeof fetch?Promise.resolve().then(()=>ta(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>ta(a))}
function va(a,b,c){return ua(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{x(`failed to asynchronously prepare wasm: ${d}`);A(d)})}function wa(a,b){var c=K;return y||"function"!=typeof WebAssembly.instantiateStreaming||ra(c)||"function"!=typeof fetch?va(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){x(`wasm streaming compile failed: ${f}`);x("falling back to ArrayBuffer instantiation");return va(c,a,b)}))}
var xa=a=>{for(;0<a.length;)a.shift()(h)},ya,L=a=>{for(var b="";D[a];)b+=ya[D[a++]];return b},M={},N={},P={},Q,za=a=>{throw new Q(a);},Aa,Ba=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Aa("Mismatched type converter count");for(var l=0;l<d.length;++l)R(d[l],k[l])}var d=[];d.forEach(function(k){P[k]=a});var f=Array(a.length),g=[],n=0;a.forEach((k,l)=>{N.hasOwnProperty(k)?f[l]=N[k]:(g.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(()=>{f[l]=N[k];++n;n===g.length&&c(f)}))});0===g.length&&
c(f)};function Ca(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(a)){if(c.Y)return;throw new Q(`Cannot register type '${d}' twice`);}N[a]=b;delete P[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(f=>f()))}function R(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Ca(a,b,c)}
var Da=[],S=[],Ea=a=>{9<a&&0===--S[a+1]&&(S[a]=void 0,Da.push(a))},T=a=>{if(!a)throw new Q("Cannot use deleted val. handle = "+a);return S[a]},U=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Da.pop()||S.length;S[b]=a;S[b+1]=1;return b}};function Fa(a){return this.fromWireType(H[a>>2])}
var Ga={name:"emscripten::val",fromWireType:a=>{var b=T(a);Ea(a);return b},toWireType:(a,b)=>U(b),argPackAdvance:8,readValueFromPointer:Fa,R:null},Ha=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ha[c>>2])};case 8:return function(c){return this.fromWireType(ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},V=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ia=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ja(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].R)return!0;return!1}function Ka(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=V(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var La=(a,b)=>{if(void 0===h[a].O){var c=h[a];h[a]=function(...d){if(!h[a].O.hasOwnProperty(d.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].O})!`);return h[a].O[d.length].apply(this,d)};h[a].O=[];h[a].O[c.X]=c}},Ma=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].O&&void 0!==h[a].O[c])throw new Q(`Cannot register public name '${a}' twice`);La(a,a);if(h.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].O[c]=b}else h[a]=b,void 0!==c&&(h[a].da=c)},Na=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(H[b+4*d>>2]);return c},Oa,Pa=(a,b,c=[])=>a.includes("j")?(0,h["dynCall_"+a])(b,...c):Oa.get(b)(...c),Qa=(a,b)=>(...c)=>Pa(a,b,c),Ra=(a,b)=>{a=L(a);var c=a.includes("j")?Qa(a,b):Oa.get(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c},Sa,Ua=a=>{a=Ta(a);var b=L(a);W(a);return b},Va=(a,b)=>{function c(g){f[g]||N[g]||(P[g]?P[g].forEach(c):(d.push(g),f[g]=!0))}
var d=[],f={};b.forEach(c);throw new Sa(`${a}: `+d.map(Ua).join([", "]));},Wa=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Za=(a,b,c)=>{switch(b){case 1:return c?d=>C[d]:d=>D[d];case 2:return c?d=>E[d>>1]:d=>F[d>>1];case 4:return c?d=>G[d>>2]:d=>H[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},$a=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=
g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}},ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,X=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&bb)return bb.decode(a.subarray(b,
c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var n=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|n:(f&7)<<18|g<<12|n<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},cb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,db=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&F[c];)++c;c<<=1;if(32<c-a&&cb)return cb.decode(D.subarray(a,
c));c="";for(d=0;!(d>=b/2);++d){var f=E[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},eb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d},fb=a=>2*a.length,gb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d},hb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=
b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d},ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},jb={},kb=a=>{var b=jb[a];return void 0===b?L(a):b},lb=[],mb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),nb=a=>{var b=lb.length;lb.push(a);return b},ob=(a,b)=>{var c=N[a];if(void 0===c)throw a=
`${b} has unknown type ${Ua(a)}`,new Q(a);return c},pb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=ob(H[b+4*d>>2],"parameter "+d);return c},qb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(H[b>>2]=U(d));return a},rb={},tb=()=>{if(!sb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in rb)void 0===rb[b]?delete a[b]:a[b]=rb[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);sb=c}return sb},sb,ub=[null,[],[]],Y=a=>0===a%4&&(0!==a%100||0===a%400),vb=[31,29,31,30,31,30,31,31,30,31,30,31],wb=[31,28,31,30,31,30,31,31,30,31,30,31];function xb(a){var b=Array(ab(a)+1);$a(a,b,0,b.length);return b}
for(var yb=(a,b,c,d)=>{function f(e,q,t){for(e="number"==typeof e?e.toString():e||"";e.length<q;)e=t[0]+e;return e}function g(e,q){return f(e,q,"0")}function n(e,q){function t(z){return 0>z?-1:0<z?1:0}var u;0===(u=t(e.getFullYear()-q.getFullYear()))&&0===(u=t(e.getMonth()-q.getMonth()))&&(u=t(e.getDate()-q.getDate()));return u}function k(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function l(e){var q=e.S;for(e=new Date((new Date(e.T+1900,0,1)).getTime());0<q;){var t=e.getMonth(),u=(Y(e.getFullYear())?vb:wb)[t];if(q>u-e.getDate())q-=u-e.getDate()+1,e.setDate(1),11>t?e.setMonth(t+1):(e.setMonth(0),e.setFullYear(e.getFullYear()+1));else{e.setDate(e.getDate()+q);break}}t=new Date(e.getFullYear()+1,0,4);q=k(new Date(e.getFullYear(),0,
4));t=k(t);return 0>=n(q,e)?0>=n(t,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var m=H[d+40>>2];d={ba:G[d>>2],aa:G[d+4>>2],U:G[d+8>>2],W:G[d+12>>2],V:G[d+16>>2],T:G[d+20>>2],P:G[d+24>>2],S:G[d+28>>2],ea:G[d+32>>2],$:G[d+36>>2],ca:m?m?X(D,m):"":""};c=c?X(D,c):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");m={"%a":e=>B[e.P].substring(0,3),"%A":e=>B[e.P],"%b":e=>r[e.V].substring(0,3),"%B":e=>r[e.V],"%C":e=>g((e.T+1900)/100|0,2),"%d":e=>
g(e.W,2),"%e":e=>f(e.W,2," "),"%g":e=>l(e).toString().substring(2),"%G":l,"%H":e=>g(e.U,2),"%I":e=>{e=e.U;0==e?e=12:12<e&&(e-=12);return g(e,2)},"%j":e=>{for(var q=0,t=0;t<=e.V-1;q+=(Y(e.T+1900)?vb:wb)[t++]);return g(e.W+q,3)},"%m":e=>g(e.V+1,2),"%M":e=>g(e.aa,2),"%n":()=>"\n","%p":e=>0<=e.U&&12>e.U?"AM":"PM","%S":e=>g(e.ba,2),"%t":()=>"\t","%u":e=>e.P||7,"%U":e=>g(Math.floor((e.S+7-e.P)/7),2),"%V":e=>{var q=Math.floor((e.S+7-(e.P+6)%7)/7);2>=(e.P+371-e.S-2)%7&&q++;if(q)53==q&&(t=(e.P+371-e.S)%7,
4==t||3==t&&Y(e.T)||(q=1));else{q=52;var t=(e.P+7-e.S-1)%7;(4==t||5==t&&Y(e.T%400-1))&&q++}return g(q,2)},"%w":e=>e.P,"%W":e=>g(Math.floor((e.S+7-(e.P+6)%7)/7),2),"%y":e=>(e.T+1900).toString().substring(2),"%Y":e=>e.T+1900,"%z":e=>{e=e.$;var q=0<=e;e=Math.abs(e)/60;return(q?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":e=>e.ca,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](d)));c=c.replace(/\0\0/g,"%");p=xb(c);if(p.length>b)return 0;
C.set(p,a);return p.length-1},zb=Array(256),Ab=0;256>Ab;++Ab)zb[Ab]=String.fromCharCode(Ab);ya=zb;Q=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Aa=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};S.push(0,1,void 0,1,null,1,!0,1,!1,1);h.count_emval_handles=()=>S.length/2-5-Da.length;
Sa=h.UnboundTypeError=((a,b)=>{var c=V(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Cb={q:()=>{},z:(a,b,c,d)=>{b=L(b);R(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(f){return this.fromWireType(D[f])},R:null})},y:a=>R(a,Ga),k:(a,b,c)=>{b=L(b);R(a,{name:b,fromWireType:d=>d,toWireType:(d,f)=>f,argPackAdvance:8,readValueFromPointer:Ha(b,c),R:null})},g:(a,b,c,d,f,g,n)=>{var k=Na(b,c);a=L(a);a=Wa(a);f=Ra(d,f);Ma(a,function(){Va(`Cannot call ${a} due to unbound types`,k)},b-1);Ba(k,l=>{var m=a;var p=
a;l=[l[0],null].concat(l.slice(1));var B=f,r=l.length;if(2>r)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var e=null!==l[1]&&!1,q=Ja(l),t="void"!==l[0].name;B=[p,za,B,g,Ia,l[0],l[1]];for(var u=0;u<r-2;++u)B.push(l[u+2]);if(!q)for(u=e?1:2;u<l.length;++u)null!==l[u].R&&B.push(l[u].R);q=Ja(l);u=l.length;var z="",O="";for(r=0;r<u-2;++r)z+=(0!==r?", ":"")+"arg"+r,O+=(0!==r?", ":"")+"arg"+r+"Wired";z=`\n        return function (${z}) {\n        if (arguments.length !== ${u-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${u-2}');\n        }`;q&&(z+="var destructors = [];\n");var Xa=q?"destructors":"null",oa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");e&&(z+="var thisWired = classParam['toWireType']("+Xa+", this);\n");for(r=0;r<u-2;++r)z+="var arg"+r+"Wired = argType"+r+"['toWireType']("+Xa+", arg"+r+");\n",oa.push("argType"+r);e&&(O="thisWired"+(0<O.length?
", ":"")+O);z+=(t||n?"var rv = ":"")+"invoker(fn"+(0<O.length?", ":"")+O+");\n";if(q)z+="runDestructors(destructors);\n";else for(r=e?1:2;r<l.length;++r)e=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==l[r].R&&(z+=`${e}_dtor(${e});\n`,oa.push(`${e}_dtor`));t&&(z+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Ya,Eb]=[oa,z+"}\n"];Ya.push(Eb);l=Ka(Ya)(...B);p=V(p,l);l=b-1;if(!h.hasOwnProperty(m))throw new Aa("Replacing nonexistant public symbol");void 0!==h[m].O&&void 0!==l?h[m].O[l]=p:
(h[m]=p,h[m].X=l);return[]})},b:(a,b,c,d,f)=>{b=L(b);-1===f&&(f=4294967295);f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g}var n=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};R(a,{name:b,fromWireType:f,toWireType:n,argPackAdvance:8,readValueFromPointer:Za(b,c,0!==d),R:null})},a:(a,b,c)=>{function d(g){return new f(C.buffer,H[g+4>>2],H[g>>2])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);R(a,{name:c,fromWireType:d,
argPackAdvance:8,readValueFromPointer:d},{Y:!0})},l:(a,b)=>{b=L(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var f=H[d>>2],g=d+4;if(c)for(var n=g,k=0;k<=f;++k){var l=g+k;if(k==f||0==D[l]){n=n?X(D,n,l-n):"";if(void 0===m)var m=n;else m+=String.fromCharCode(0),m+=n;n=l+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(D[g+k]);m=m.join("")}W(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"==typeof f;if(!(g||f instanceof
Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array))throw new Q("Cannot pass non-string to std::string");var n=c&&g?ab(f):f.length;var k=Bb(4+n+1),l=k+4;H[k>>2]=n;if(c&&g)$a(f,D,l,n+1);else if(g)for(g=0;g<n;++g){var m=f.charCodeAt(g);if(255<m)throw W(l),new Q("String has UTF-16 code units that do not fit in 8 bits");D[l+g]=m}else for(g=0;g<n;++g)D[l+g]=f[g];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:Fa,R(d){W(d)}})},f:(a,b,c)=>{c=L(c);if(2===b){var d=db;
var f=eb;var g=fb;var n=k=>F[k>>1]}else 4===b&&(d=gb,f=hb,g=ib,n=k=>H[k>>2]);R(a,{name:c,fromWireType:k=>{for(var l=H[k>>2],m,p=k+4,B=0;B<=l;++B){var r=k+4+B*b;if(B==l||0==n(r))p=d(p,r-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=p),p=r+b}W(k);return m},toWireType:(k,l)=>{if("string"!=typeof l)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var m=g(l),p=Bb(4+m+b);H[p>>2]=m/b;f(l,p+4,m+b);null!==k&&k.push(W,p);return p},argPackAdvance:8,readValueFromPointer:Fa,R(k){W(k)}})},A:(a,b)=>
{b=L(b);R(a,{Z:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},e:(a,b,c,d,f)=>{a=lb[a];b=T(b);c=kb(c);return a(b,b[c],d,f)},B:Ea,n:a=>{if(0===a)return U(mb());a=kb(a);return U(mb()[a])},d:(a,b,c)=>{b=pb(a,b);var d=b.shift();a--;var f="return function (obj, func, destructorsRef, args) {\n",g=0,n=[];0===c&&n.push("obj");for(var k=["retType"],l=[d],m=0;m<a;++m)n.push("arg"+m),k.push("argType"+m),l.push(b[m]),f+=`  var arg${m} = argType${m}.readValueFromPointer(args${g?"+"+g:""});\n`,
g+=b[m].argPackAdvance;f+=`  var rv = ${1===c?"new func":"func.call"}(${n.join(", ")});\n`;d.Z||(k.push("emval_returnValue"),l.push(qb),f+="  return emval_returnValue(retType, destructorsRef, rv);\n");k.push(f+"};\n");a=Ka(k)(...l);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return nb(V(c,a))},i:(a,b)=>{a=T(a);b=T(b);return U(a[b])},c:a=>{9<a&&(S[a+1]+=1)},m:a=>U(kb(a)),o:a=>{var b=T(a);Ia(b);Ea(a)},h:(a,b)=>{a=ob(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},
j:()=>{A("")},x:()=>{A("OOM")},s:(a,b)=>{var c=0;tb().forEach((d,f)=>{var g=b+c;f=H[a+4*f>>2]=g;for(g=0;g<d.length;++g)C[f++]=d.charCodeAt(g);C[f]=0;c+=d.length+1});return 0},t:(a,b)=>{var c=tb();H[a>>2]=c.length;var d=0;c.forEach(f=>d+=f.length+1);H[b>>2]=d;return 0},u:()=>52,w:()=>52,p:function(){return 70},v:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var n=H[b>>2],k=H[b+4>>2];b+=8;for(var l=0;l<k;l++){var m=D[n+l],p=ub[a];0===m||10===m?((1===a?da:x)(X(p,0)),p.length=0):p.push(m)}f+=k}H[d>>2]=f;return 0},
r:(a,b,c,d)=>yb(a,b,c,d)},Z=function(){function a(c){Z=c.exports;ea=Z.C;c=ea.buffer;h.HEAP8=C=new Int8Array(c);h.HEAP16=E=new Int16Array(c);h.HEAPU8=D=new Uint8Array(c);h.HEAPU16=F=new Uint16Array(c);h.HEAP32=G=new Int32Array(c);h.HEAPU32=H=new Uint32Array(c);h.HEAPF32=ha=new Float32Array(c);h.HEAPF64=ia=new Float64Array(c);Oa=Z.G;ka.unshift(Z.D);I--;h.monitorRunDependencies?.(I);0==I&&(null!==pa&&(clearInterval(pa),pa=null),J&&(c=J,J=null,c()));return Z}var b={a:Cb};I++;h.monitorRunDependencies?.(I);
if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){x(`Module.instantiateWasm callback failed with error: ${c}`),v(c)}wa(b,function(c){a(c.instance)}).catch(v);return{}}(),Bb=a=>(Bb=Z.E)(a),Ta=a=>(Ta=Z.F)(a),W=a=>(W=Z.H)(a),qa=()=>(qa=Z.I)();h.dynCall_viijii=(a,b,c,d,f,g,n)=>(h.dynCall_viijii=Z.J)(a,b,c,d,f,g,n);h.dynCall_jiji=(a,b,c,d,f)=>(h.dynCall_jiji=Z.K)(a,b,c,d,f);h.dynCall_iiiiij=(a,b,c,d,f,g,n)=>(h.dynCall_iiiiij=Z.L)(a,b,c,d,f,g,n);
h.dynCall_iiiiijj=(a,b,c,d,f,g,n,k,l)=>(h.dynCall_iiiiijj=Z.M)(a,b,c,d,f,g,n,k,l);h.dynCall_iiiiiijj=(a,b,c,d,f,g,n,k,l,m)=>(h.dynCall_iiiiiijj=Z.N)(a,b,c,d,f,g,n,k,l,m);var Db;J=function Fb(){Db||Gb();Db||(J=Fb)};
function Gb(){function a(){if(!Db&&(Db=!0,h.calledRun=!0,!fa)){ma=!0;xa(ka);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();la.unshift(b)}xa(la)}}if(!(0<I)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)na();xa(ja);0<I||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Gb();


  return moduleArg.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = MeshGenerator;
else if (typeof define === 'function' && define['amd'])
  define([], () => MeshGenerator);
